spring.application.name=checkdesk
server.port=8080

spring.datasource.url=jdbc:postgresql://postgres/checkdesc
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.url=jdbc:postgresql://postgres/checkdesc
spring.liquibase.user=postgres
spring.liquibase.password=password
spring.liquibase.change-log=classpath:db/dbchangelog.xml
spring.liquibase.enabled=true