apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checkdesc-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /desc
            pathType: Prefix
            backend:
              service:
                name: checkdesc
                port:
                  number: 8080

          - path: /exam
            pathType: Prefix
            backend:
              service:
                name: checkexam
                port:
                  number: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https